# Site settings
title: "In defense of degrowth"
email:
description: > # this means to ignore newlines until "baseurl:"
  The idea of degrowth is contentious, often misunderstood, and (perhaps paradoxically) growing in popularity. In this book, Giorgos Kallis, one of the movement's leading thinkers, presents an accessible, inspiring, and enjoyable defense.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://indefenseofdegrowth.com" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
