# Site settings
title: "In defense of degrowth"
email:
description: > # this means to ignore newlines until "baseurl:"
  TODO: Fill me in
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://indefenseofdegrowth.com" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
